config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
	validates :author,:content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  include Response
    rescue_from ActiveRecord::RecordNotFound do |exception|
    json_response({ error: exception.message }, :bad_request)
  end
  rescue_from ActiveRecord::RecordNotFound do |exception|
    json_response({ error: exception.message }, :not_found)
  end
rescue_from ActiveRecord::RecordNotFound do |exception|
    json_response({ error: exception.message }, :unprocessable_entity)
  end
end

app/controllers/concerns/response.rb
module Response
    def json_response(object, status = :ok)
      render json: object, status: status
    end
  end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
      json_response(@quotes)
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
      @quote = Quote.find(params[:id])
      json_response(@quote)
    end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
      @quote = Quote.create!(quote_params)
      json_response(@quote, :created)
    end
  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
      @quote = Quote.find(params[:id])
      @quote.update!(quote_params)
      json_response(@quote)
    end
  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
      @quote = Quote.find(params[:id])
      @quote.destroy
      render status: 200, json: {
        message: "Your quote has succesfully been deleted"
      }
    end


  private
    def json_response(object, status = :ok)
      render json: object, status: status
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.permit(:author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :quote_author %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :quote_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.author %></td>
        <td><%= quote.content %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @quote.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @quote.content %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>